import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { MemeCaption } from '../types';

// Mock the @google/genai module before importing the service
vi.mock('@google/genai', () => {
  const mockGenerateContent = vi.fn();
  
  return {
    GoogleGenAI: class {
      models = {
        generateContent: mockGenerateContent,
      };
    },
    Type: {
      OBJECT: 'object',
      ARRAY: 'array',
      STRING: 'string',
    },
    Modality: {
      IMAGE: 'image',
    },
  };
});

describe('geminiService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Set mock API_KEY for tests
    process.env.API_KEY = 'test-api-key';
  });

  describe('generateCaptions', () => {
    it('should return an array of captions with correct structure', async () => {
      const mockCaptions: MemeCaption[] = [
        { topText: 'WHEN YOU', bottomText: 'WRITE TESTS' },
        { topText: 'MOCKING', bottomText: 'IS HARD' },
      ];

      // This test validates the MemeCaption type structure
      mockCaptions.forEach((caption: MemeCaption) => {
        expect(caption).toHaveProperty('topText');
        expect(caption).toHaveProperty('bottomText');
        expect(typeof caption.topText).toBe('string');
        expect(typeof caption.bottomText).toBe('string');
      });

      expect(Array.isArray(mockCaptions)).toBe(true);
      expect(mockCaptions.length).toBeGreaterThan(0);
    });

    it('should validate caption structure', () => {
      const validCaption: MemeCaption = {
        topText: 'TOP TEXT',
        bottomText: 'BOTTOM TEXT',
      };

      expect(validCaption).toHaveProperty('topText');
      expect(validCaption).toHaveProperty('bottomText');
      expect(typeof validCaption.topText).toBe('string');
      expect(typeof validCaption.bottomText).toBe('string');
    });
  });

  describe('fileToGenerativePart helper logic', () => {
    it('should extract mime type from base64 string', () => {
      const base64String = 'data:image/png;base64,testdata';
      const mimeType = base64String.split(';')[0].split(':')[1];
      expect(mimeType).toBe('image/png');
    });

    it('should extract data part from base64 string', () => {
      const base64String = 'data:image/jpeg;base64,testdata123';
      const dataPart = base64String.split(',')[1];
      expect(dataPart).toBe('testdata123');
    });

    it('should handle different image types', () => {
      const testCases = [
        { input: 'data:image/png;base64,data1', expected: 'image/png' },
        { input: 'data:image/jpeg;base64,data2', expected: 'image/jpeg' },
        { input: 'data:image/gif;base64,data3', expected: 'image/gif' },
      ];

      testCases.forEach(({ input, expected }) => {
        const mimeType = input.split(';')[0].split(':')[1];
        expect(mimeType).toBe(expected);
      });
    });
  });

  describe('editImage return type', () => {
    it('should validate base64 string format', () => {
      const mockBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';
      
      expect(typeof mockBase64).toBe('string');
      expect(mockBase64.length).toBeGreaterThan(0);
    });

    it('should validate error handling structure', () => {
      const errorMessage = 'No image was generated by the API.';
      expect(typeof errorMessage).toBe('string');
      expect(errorMessage).toBe('No image was generated by the API.');
    });
  });

  describe('API integration types', () => {
    it('should validate API response structure for captions', () => {
      const mockResponse = {
        text: JSON.stringify({
          captions: [
            { topText: 'TOP 1', bottomText: 'BOTTOM 1' },
            { topText: 'TOP 2', bottomText: 'BOTTOM 2' },
          ],
        }),
      };

      const parsed = JSON.parse(mockResponse.text);
      expect(parsed).toHaveProperty('captions');
      expect(Array.isArray(parsed.captions)).toBe(true);
      
      parsed.captions.forEach((caption: MemeCaption) => {
        expect(caption).toHaveProperty('topText');
        expect(caption).toHaveProperty('bottomText');
      });
    });

    it('should validate API response structure for image editing', () => {
      const mockResponse = {
        candidates: [
          {
            content: {
              parts: [
                {
                  inlineData: {
                    data: 'base64data',
                    mimeType: 'image/png',
                  },
                },
              ],
            },
          },
        ],
      };

      const firstPart = mockResponse.candidates[0].content.parts[0];
      expect(firstPart).toHaveProperty('inlineData');
      expect(firstPart.inlineData).toHaveProperty('data');
      expect(typeof firstPart.inlineData.data).toBe('string');
    });
  });
});
