/**
 * Application configuration constants
 */

export const CANVAS_CONFIG = {
  /** Font size ratio relative to image width */
  FONT_SIZE_RATIO: 10,
  /** Stroke width ratio relative to font size */
  STROKE_WIDTH_RATIO: 20,
  /** Default font family for meme text */
  FONT_FAMILY: 'Anton',
  /** Bottom text offset from bottom edge */
  BOTTOM_TEXT_OFFSET: 20,
  /** Text color */
  TEXT_COLOR: 'white',
  /** Text stroke color */
  STROKE_COLOR: 'black',
  /** Default JPEG quality for export */
  JPEG_QUALITY: 0.9,
} as const;

export const AI_CONFIG = {
  /** Default model for caption generation */
  CAPTION_MODEL: 'gemini-2.5-flash',
  /** Default model for image editing */
  IMAGE_EDIT_MODEL: 'gemini-2.5-flash-image',
  /** Number of captions to generate */
  CAPTION_COUNT: 5,
} as const;

export const ERROR_MESSAGES = {
  API_KEY_MISSING: 'API_KEY environment variable not set',
  CAPTION_GENERATION_FAILED: 'Could not generate captions. Please try again.',
  IMAGE_EDIT_FAILED: 'Could not edit the image. Please try again.',
  DOWNLOAD_FAILED: 'Could not prepare image for download.',
  TEMPLATE_LOAD_FAILED: 'Could not load template. Please try another.',
  INVALID_FILE_TYPE: 'Please select an image file.',
  IMAGE_READ_FAILED: 'The selected file could not be read as an image.',
  FILE_READ_FAILED: 'Failed to read the selected file.',
  CANVAS_CONTEXT_FAILED: 'Could not get canvas context',
  IMAGE_LOAD_FAILED: 'Failed to load image for canvas rendering.',
  NO_IMAGE_GENERATED: 'No image was generated by the API.',
} as const;
